# Generated by Django 5.0.1 on 2024-04-07 07:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('likes_cart', '0005_cart_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10)),
                ('date_of_purchase', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('IN_PROCESS', 'In Process'), ('SEND', 'Send')], default='IN_PROCESS', max_length=20)),
                ('delivery_address', models.CharField(max_length=100)),
                ('is_personal_address', models.BooleanField(default=True)),
                ('payment_method', models.CharField(max_length=20)),
                ('comment', models.TextField()),
                ('carts', models.ManyToManyField(to='likes_cart.cart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
