# Generated by Django 5.0.1 on 2024-04-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_city_order_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CARD', 'Card payment'), ('CASH', 'Cash on deliver')], default='CASH', max_length=20),
        ),
    ]
