# Generated by Django 5.0.1 on 2024-04-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CARD', 'Card payment'), ('CASH', 'Cash on delivery')], default='CASH', max_length=20),
        ),
    ]
