# Generated by Django 5.0.1 on 2024-04-12 06:57

import clothesDjango.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='agreed_to_terms',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=10, validators=[clothesDjango.accounts.validators.validate_phone_number]),
        ),
    ]
