# Generated by Django 5.0.1 on 2024-04-12 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_copiedcart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='carts',
        ),
    ]
