# Generated by Django 5.0.1 on 2024-04-20 13:47

import clothesDjango.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_remove_order_carts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=14, validators=[clothesDjango.accounts.validators.validate_phone_number]),
        ),
    ]
