# Generated by Django 5.0.1 on 2024-04-06 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes_cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='in_cart',
            field=models.BooleanField(default=False),
        ),
    ]
