# Generated by Django 5.0.1 on 2024-04-06 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes_cart', '0002_likes_in_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='in_cart',
        ),
    ]
