# Generated by Django 5.0.1 on 2024-04-06 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes_cart', '0003_remove_likes_in_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='S', max_length=2),
        ),
    ]
