# Generated by Django 5.0.1 on 2024-03-30 22:51

import clothesDjango.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='date_of_birth',
            field=models.DateField(null=True, validators=[clothesDjango.accounts.validators.validate_age]),
        ),
    ]
