# Generated by Django 5.0.1 on 2024-03-20 17:18

import clothesDjango.accounts.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_agreed_to_terms'),
        ('catalogue', '0006_alter_cloth_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(validators=[clothesDjango.accounts.validators.validate_before_today, clothesDjango.accounts.validators.validate_age]),
        ),
        migrations.CreateModel(
            name='Ordered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_purchase', models.DateField(auto_now=True)),
                ('purchased', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.cloth')),
                ('purchases', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.user')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='orders',
            field=models.ManyToManyField(through='accounts.Ordered', to='catalogue.cloth'),
        ),
    ]
