# Generated by Django 5.0.1 on 2024-03-21 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_birth_date_ordered_user_orders'),
        ('catalogue', '0007_cloth_photo_1_cloth_photo_2_cloth_photo_3_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ordered',
            new_name='Order',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='purchased',
            new_name='to_cloth',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='purchases',
            new_name='to_user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='orders',
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_cloth', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.cloth')),
                ('to_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_cloth', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.cloth')),
                ('to_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.user')),
            ],
        ),
    ]
