# Generated by Django 5.0.1 on 2024-04-03 11:27

import clothesDjango.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_profile_address_remove_profile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[clothesDjango.accounts.validators.validate_letters_and_dashes]),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[clothesDjango.accounts.validators.validate_letters_and_dashes]),
        ),
    ]
