# Generated by Django 5.0.1 on 2024-04-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_myuser_first_name_alter_myuser_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='postal_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
