# Generated by Django 5.0.1 on 2024-03-21 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_ordered_order_rename_purchased_order_to_cloth_and_more'),
        ('catalogue', '0008_cloth_material_cloth_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='to_cloth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.cloth'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='like',
            name='to_cloth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.cloth'),
        ),
        migrations.AlterField(
            model_name='like',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_of_purchase',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='to_cloth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.cloth'),
        ),
        migrations.AlterField(
            model_name='order',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
        ),
    ]
