# Generated by Django 5.0.1 on 2024-04-04 12:03

import clothesDjango.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_myuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, validators=[clothesDjango.accounts.validators.validate_age, clothesDjango.accounts.validators.validate_before_today]),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
