# Generated by Django 5.0.1 on 2024-04-10 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_myuser_date_of_birth_delete_cart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminuser',
            options={'permissions': [('can_add_clothes', 'Can add clothes')]},
        ),
    ]
