# Generated by Django 5.0.1 on 2024-04-12 06:45

import clothesDjango.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_adminuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[clothesDjango.accounts.validators.validate_phone_number]),
        ),
        migrations.DeleteModel(
            name='ClientUser',
        ),
    ]
