# Generated by Django 5.0.1 on 2024-04-12 07:01

import clothesDjango.accounts.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_myuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.MinLengthValidator(4, message='Username must be at least 4 characters long.'), clothesDjango.accounts.validators.validate_no_spaces]),
        ),
    ]
