# Generated by Django 5.0.1 on 2024-04-20 13:47

import clothesDjango.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_myuser_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[clothesDjango.accounts.validators.validate_phone_number]),
        ),
    ]
