# Generated by Django 5.0.1 on 2024-04-21 05:29

import clothesDjango.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_myuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='postal_code',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[clothesDjango.accounts.validators.validate_numbers_only]),
        ),
    ]
