# Generated by Django 5.0.1 on 2024-03-30 11:48

import clothesDjango.catalogue.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_1', models.ImageField(blank=True, null=True, upload_to='', validators=[clothesDjango.catalogue.validators.image_size_validator])),
                ('photo_2', models.ImageField(blank=True, null=True, upload_to='', validators=[clothesDjango.catalogue.validators.image_size_validator])),
                ('photo_3', models.ImageField(blank=True, null=True, upload_to='', validators=[clothesDjango.catalogue.validators.image_size_validator])),
                ('photo_4', models.ImageField(blank=True, null=True, upload_to='', validators=[clothesDjango.catalogue.validators.image_size_validator])),
                ('photo_5', models.ImageField(blank=True, null=True, upload_to='', validators=[clothesDjango.catalogue.validators.image_size_validator])),
                ('type', models.CharField(choices=[('DRESS', 'dress'), ('T_SHIRT', 't-shirt'), ('JEANS', 'jeans'), ('SKIRT', 'skirt'), ('BLOUSE', 'blouse'), ('JACKET', 'jacket'), ('TROUSERS', 'trousers'), ('SOCKS', 'socks'), ('TOP', 'top'), ('UNDERWEAR', 'underwear')], max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('color', models.CharField(max_length=20)),
                ('material', models.CharField(max_length=20, null=True)),
                ('size', models.CharField(max_length=100, null=True)),
                ('stocked_S', models.PositiveIntegerField(default=0)),
                ('stocked_M', models.PositiveIntegerField(default=0)),
                ('stocked_L', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Clothes',
                'ordering': ['price'],
            },
        ),
    ]
