# Generated by Django 5.0.1 on 2024-03-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('tshirt', 'tshirt'), ('jeans', 'jeans'), ('skirt', 'skirt'), ('blouse', 'blouse'), ('jacket', 'jacket'), ('trousers', 'trousers'), ('socks', 'socks'), ('top', 'top'), ('underwear', 'underwear')], max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=20)),
                ('size', models.CharField(max_length=10)),
            ],
        ),
    ]
