# Generated by Django 5.0.1 on 2024-04-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloth',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='clothes_images'),
        ),
    ]
