# Generated by Django 5.0.1 on 2024-03-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_cloth_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloth',
            name='stocked_L',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cloth',
            name='stocked_M',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cloth',
            name='stocked_S',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
