# Generated by Django 5.0.1 on 2024-04-10 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_cloth_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloth',
            name='photo_2',
        ),
        migrations.RemoveField(
            model_name='cloth',
            name='photo_3',
        ),
        migrations.RemoveField(
            model_name='cloth',
            name='photo_4',
        ),
        migrations.RemoveField(
            model_name='cloth',
            name='photo_5',
        ),
    ]
