# Generated by Django 5.0.1 on 2024-04-10 18:22

import clothesDjango.catalogue.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_remove_cloth_photo_2_remove_cloth_photo_3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloth',
            name='photo_1',
        ),
        migrations.AlterField(
            model_name='cloth',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='clothes_images', validators=[clothesDjango.catalogue.validators.image_size_validator]),
        ),
    ]
