# Generated by Django 5.0.1 on 2024-03-17 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_cloth_stocked_l_cloth_stocked_m_cloth_stocked_s'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloth',
            name='size',
        ),
    ]
