# Generated by Django 5.0.1 on 2024-04-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_remove_cloth_photo_1_alter_cloth_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
