# Generated by Django 5.0.1 on 2024-03-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_remove_cloth_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='type',
            field=models.CharField(choices=[('DRESS', 'dress'), ('T_SHIRT', 't-shirt'), ('JEANS', 'jeans'), ('SKIRT', 'skirt'), ('BLOUSE', 'blouse'), ('JACKET', 'jacket'), ('TROUSERS', 'trousers'), ('SOCKS', 'socks'), ('TOP', 'top'), ('UNDERWEAR', 'underwear')], max_length=50),
        ),
    ]
