# Generated by Django 5.0.1 on 2024-04-17 11:47

import clothesDjango.catalogue.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_alter_cloth_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloth',
            name='photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='clothes_images', validators=[clothesDjango.catalogue.validators.image_size_validator]),
        ),
        migrations.AddField(
            model_name='cloth',
            name='photo_3',
            field=models.ImageField(blank=True, null=True, upload_to='clothes_images', validators=[clothesDjango.catalogue.validators.image_size_validator]),
        ),
        migrations.AddField(
            model_name='cloth',
            name='photo_4',
            field=models.ImageField(blank=True, null=True, upload_to='clothes_images', validators=[clothesDjango.catalogue.validators.image_size_validator]),
        ),
        migrations.AddField(
            model_name='cloth',
            name='photo_5',
            field=models.ImageField(blank=True, null=True, upload_to='clothes_images', validators=[clothesDjango.catalogue.validators.image_size_validator]),
        ),
    ]
