# Generated by Django 5.0.1 on 2024-03-20 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_alter_cloth_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cloth',
            options={'ordering': ['price'], 'verbose_name_plural': 'Clothes'},
        ),
    ]
