# Generated by Django 5.0.1 on 2024-04-17 11:59

import clothesDjango.catalogue.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_cloth_photo_2_cloth_photo_3_cloth_photo_4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloth',
            name='photo_6',
            field=models.ImageField(blank=True, null=True, upload_to='clothes_images', validators=[clothesDjango.catalogue.validators.image_size_validator]),
        ),
    ]
