# Generated by Django 5.0.1 on 2024-03-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_cloth_photo_1_cloth_photo_2_cloth_photo_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloth',
            name='material',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cloth',
            name='size',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
