# Generated by Django 5.0.1 on 2024-04-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0008_alter_cloth_photo_alter_cloth_photo_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='type',
            field=models.CharField(choices=[('DRESS', 'dress'), ('T_SHIRT', 't-shirt'), ('JEANS', 'jeans'), ('SKIRT', 'skirt'), ('BLOUSE', 'blouse'), ('JACKET', 'jacket'), ('TROUSERS', 'trousers'), ('SOCKS', 'socks'), ('TOP', 'top'), ('UNDERWEAR', 'underwear'), ('SWEATSHIRT', 'sweatshirt'), ('TRACK_SUIT', 'track-suit')], max_length=50),
        ),
    ]
