# Generated by Django 5.0.1 on 2024-03-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0008_cloth_material_cloth_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloth',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
