# Generated by Django 5.0.1 on 2024-04-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0009_alter_cloth_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='material',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
