# Generated by Django 5.0.1 on 2024-04-17 13:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0010_alter_cloth_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloth',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
