# Generated by Django 5.0.1 on 2024-04-21 06:45

import clothesDjango.catalogue.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0012_alter_cloth_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='color',
            field=models.CharField(max_length=20, validators=[clothesDjango.catalogue.validators.validate_letters_and_spaces]),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='description',
            field=models.TextField(blank=True, null=True, validators=[clothesDjango.catalogue.validators.validate_letters_and_spaces]),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='material',
            field=models.CharField(max_length=50, null=True, validators=[clothesDjango.catalogue.validators.validate_letters_and_spaces]),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='name',
            field=models.CharField(max_length=100, validators=[clothesDjango.catalogue.validators.validate_letters_and_spaces]),
        ),
    ]
