# Generated by Django 5.0.1 on 2024-04-21 06:49

import clothesDjango.catalogue.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0013_alter_cloth_color_alter_cloth_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='material',
            field=models.CharField(default='mixture of bio materials', max_length=50, validators=[clothesDjango.catalogue.validators.validate_letters_and_spaces]),
        ),
    ]
