# Generated by Django 5.0.1 on 2024-04-15 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_remove_testimonial_author_remove_testimonial_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='phone',
        ),
    ]
