# Generated by Django 5.0.1 on 2024-03-20 17:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_testimonial_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='text',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
