# Generated by Django 5.0.1 on 2024-03-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_testimonial_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='email',
            field=models.EmailField(default='some@email.com', max_length=254),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
