# Generated by Django 5.0.1 on 2024-03-22 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_testimonial_email_testimonial_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed', models.CharField(max_length=20)),
            ],
        ),
    ]
