# Generated by Django 5.0.1 on 2024-03-22 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='subscribed',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
