# Generated by Django 5.0.1 on 2024-03-23 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_alter_newsletter_subscribed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
